module.exports = {
  important: true,
  purge: {
    content: ["./src/**/*.tsx"],
    options: {
      safelist: [
        "text-spotify",
        "text-youtube",
        "bg-youtube",
        "bg-spotify",
        "text-primary",
        "text-primary-dark",
        "text-foreground-secondary",
        "text-foreground-tertiary",
        "text-foreground-backdrop",
        "w-1",
        "w-2",
        "w-4",
        "w-8",
        "w-10",
        "w-12",
        "w-20",
        "w-32",
        "w-40",
        "w-full",
        "h-1",
        "h-2",
        "h-4",
        "h-6",
        "h-8",
        "h-10",
        "h-12",
        "h-full",
        "text-xs",
        "text-sm",
        "text-md",
        "text-lg",
        "text-xl",
        "text-2xl",
        "text-3xl",
        "text-4xl",
        "text-center",
        "text-left",
        "text-right",
        "justify-start",
        "justify-end",
        "justify-center",
        "justify-between",
        "justify-around",
        "justify-evenly",
        "items-stretch",
        "items-end",
        "items-start",
        "items-center",
        "items-baseline",
      ],
    },
  },
  darkMode: false,
  theme: {
    colors: {
      background: {
        DEFAULT: "hsl(265deg 43% 5%)",
        secondary: "hsl(266deg 44% 7%)",
        tertiary: "hsl(264deg 43% 9%)",
        bar: "hsl(265deg 43% 11%)",
        backdrop: "hsl(264deg 40% 12% / 30%)",
      },
      foreground: {
        DEFAULT: "hsl(270deg 4% 91%)",
        secondary: "hsla(270deg 4% 91% / 85%)",
        tertiary: "hsla(270deg 4% 91% / 70%)",
        backdrop: "hsla(263deg 20% 18% / 50%)",
      },
      danger: {
        DEFAULT: "#d7373f",
        light: "#e34850",
        dark: "#c9252d",
        label: "#fff",
      },
      primary: {
        DEFAULT: "hsl(349,100%,59%)",
        dark: "hsl(349,67%,49%)",
        label: "#fff",
      },
      secondary: {
        DEFAULT: "hsl(37,91%,55%)",
        light: "hsl(37,91%,65%)",
        dark: "hsl(37,91%,50%)",
        label: "#000",
      },
      black: "#000",
      white: "#fff",
      transparent: "transparent",
      youtube: {
        DEFAULT: "#f00",
        label: "#fff",
      },
      spotify: {
        DEFAULT: "#1db954",
        label: "#fff",
      },
    },
    fontWeight: {
      normal: 400,
      bold: 700,
    },
    opacity: {
      0: "0",
      25: "0.25",
      50: "0.5",
      75: "0.75",
      100: "1",
    },
  },
  variants: {
    extend: {},
  },
  plugins: [
    function ({ addComponents }) {
      addComponents({
        ".container": {
          maxWidth: "calc(100vw - 1.4rem)",
          margin: "0 auto",
          "@screen sm": {
            maxWidth: "calc(100vw - 1.4rem)",
          },
          "@screen md": {
            maxWidth: "calc(100vw - 2.8rem)",
          },
          "@screen lg": {
            maxWidth: "calc(100vw - 5.6rem)",
          },
        },
      });
    },
  ],
};
