export const Config = {
  API_URI: process.env.REACT_APP_API_URI,
  APP_URI: process.env.REACT_APP_APP_URI,
  WEBSOCKET_URI: process.env.REACT_APP_WEBSOCKET_URI,
  SPOTIFY_CLIENT_ID: process.env.REACT_APP_SPOTIFY_CLIENT_ID,
  MAPBOX_ACCESS_TOKEN: process.env.REACT_APP_MAPBOX_ACCESS_TOKEN,
  FACEBOOK_APP_ID: process.env.REACT_APP_FACEBOOK_APP_ID,
};
