// @ts-nocheck
import { wrapIcon } from "./wrapIcon";
import { Activity } from "./exports";
export const IconActivity = wrapIcon(Activity);
import { ArrowRight } from "./exports";
export const IconArrowRight = wrapIcon(ArrowRight);
import { Bell } from "./exports";
export const IconBell = wrapIcon(Bell);
import { Check } from "./exports";
export const IconCheck = wrapIcon(Check);
import { ChevronDown } from "./exports";
export const IconChevronDown = wrapIcon(ChevronDown);
import { ChevronLeft } from "./exports";
export const IconChevronLeft = wrapIcon(ChevronLeft);
import { ChevronRight } from "./exports";
export const IconChevronRight = wrapIcon(ChevronRight);
import { ChevronUp } from "./exports";
export const IconChevronUp = wrapIcon(ChevronUp);
import { Edit } from "./exports";
export const IconEdit = wrapIcon(Edit);
import { Facebook } from "./exports";
export const IconFacebook = wrapIcon(Facebook);
import { GoogleColor } from "./exports";
export const IconGoogleColor = wrapIcon(GoogleColor);
import { Headphones } from "./exports";
export const IconHeadphones = wrapIcon(Headphones);
import { Home } from "./exports";
export const IconHome = wrapIcon(Home);
import { LogIn } from "./exports";
export const IconLogIn = wrapIcon(LogIn);
import { Logo } from "./exports";
export const IconLogo = wrapIcon(Logo);
import { MapPin } from "./exports";
export const IconMapPin = wrapIcon(MapPin);
import { Menu } from "./exports";
export const IconMenu = wrapIcon(Menu);
import { MessageSquare } from "./exports";
export const IconMessageSquare = wrapIcon(MessageSquare);
import { MoreHorizontal } from "./exports";
export const IconMoreHorizontal = wrapIcon(MoreHorizontal);
import { MoreVertical } from "./exports";
export const IconMoreVertical = wrapIcon(MoreVertical);
import { Music } from "./exports";
export const IconMusic = wrapIcon(Music);
import { Pause } from "./exports";
export const IconPause = wrapIcon(Pause);
import { PlayListAdd } from "./exports";
export const IconPlayListAdd = wrapIcon(PlayListAdd);
import { Play } from "./exports";
export const IconPlay = wrapIcon(Play);
import { Plus } from "./exports";
export const IconPlus = wrapIcon(Plus);
import { Reddit } from "./exports";
export const IconReddit = wrapIcon(Reddit);
import { Search } from "./exports";
export const IconSearch = wrapIcon(Search);
import { Send } from "./exports";
export const IconSend = wrapIcon(Send);
import { Settings } from "./exports";
export const IconSettings = wrapIcon(Settings);
import { Share2 } from "./exports";
export const IconShare2 = wrapIcon(Share2);
import { SkipBack } from "./exports";
export const IconSkipBack = wrapIcon(SkipBack);
import { SkipForward } from "./exports";
export const IconSkipForward = wrapIcon(SkipForward);
import { Spotify } from "./exports";
export const IconSpotify = wrapIcon(Spotify);
import { Twitter } from "./exports";
export const IconTwitter = wrapIcon(Twitter);
import { UserPlus } from "./exports";
export const IconUserPlus = wrapIcon(UserPlus);
import { User } from "./exports";
export const IconUser = wrapIcon(User);
import { Users } from "./exports";
export const IconUsers = wrapIcon(Users);
import { X } from "./exports";
export const IconX = wrapIcon(X);
import { Youtube } from "./exports";
export const IconYoutube = wrapIcon(Youtube);
